# REF: https://github.com/stats-organization/github-readme-stats-action#readme
# REF: https://github.com/yoshi389111/github-profile-3d-contrib

name: Profile Cards

on:
  schedule:
    # https://docs.github.com/zh/actions/using-workflows/events-that-trigger-workflows#schedule
    # 每天 00:00 运行
    - cron: "0 0 * * *"
      timezone: "Etc/GMT-8"
  
  # allows to manually run the job at any time
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-profile-cards
    steps:
      - uses: actions/checkout@v5

      - name: Generate profile 3D contribution card
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: ./configs/profile-3d-contrib.json

      - name: Generate stats light card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&include_all_commits=true&show=reviews,discussions_started,discussions_answered,prs_merged,prs_merged_percentage&theme=buefy
          path: profile-stats/stats-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate stats dark card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&include_all_commits=true&show=reviews,discussions_started,discussions_answered,prs_merged,prs_merged_percentage&theme=nord
          path: profile-stats/stats-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top-langs light card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=20&show_icons=true&hide=jupyter%20notebook&theme=buefy
          path: profile-stats/top-langs-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top-langs dark card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=20&show_icons=true&hide=jupyter%20notebook&theme=nord
          path: profile-stats/top-langs-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile-stats/*.svg
          git add profile-3d-contrib/*.svg
          git commit -m "Update README cards" || exit 0
          git push
